pmt_dbt:
  outputs:

    dev:
      type: postgres
      threads: 2
      host: theory.bcgov
      port: 5443
      user: dlh_admin_user
      pass: "{{ env_var('dlh_password') }}"
      dbname: lhousedev
      schema: public
      
    test:
      type: postgres
      threads: 2
      host: theory.bcgov
      port: 5444
      user: dlh_admin_user
      pass: "{{ env_var('dlh_password') }}" 
      dbname: lhousetst
      schema: public

    prod:
      type: postgres
      threads: 2
      host: existence.bcgov
      port: 5436
      user: dlh_admin_user
      pass: "{{ env_var('dlh_password') }}" 
      dbname: lhouseprd
      schema: public
      
  target: dev
